import os
print("Computer Vision Analytics Service")
print("Step 1 : Create YAML File")
os.system("python Create_YAML.py")
print("Step 2: Add Timestamp to video files")
os.system("python add_timestamp_ffmeg.py")
print("Step 3: Annotation Service")
os.system("python AnnotationService.py")
print("Step 4: Upload the source videos to Azure Blob")
os.system("python Upload.py")
print("Step 5: Download the files from Azure Blob")
os.system("python DownloadBlob.py")
print("Step 6: Yolo Algo")
os.system("python Yolo.py")
print("Step 7: Upload Algo")
os.system("python Upload.py")
print("Process completed!!")